//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("SUDOKU_Regular")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("4.1.2.1")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("SUDOKU_Regular")]
[assembly: System.Reflection.AssemblyTitleAttribute("SUDOKU_Regular")]
[assembly: System.Reflection.AssemblyVersionAttribute("4.1.2.1")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows10.0.22621.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows10.0.22621.0")]

// MSBuild WriteCodeFragment クラスによって生成されました。

